### ISSUE TITLE
Join entre twig et helper

### ISSUE THREAD

**Issue by robbee** [twigy/twigy-server#1]
Hello 

Voila le p'tit truc que j'arrive pas a faire dans le twig controler mais avant un peu de vocabulaire... 

- Un TWIG est un objet qui reprend plusieurs objets.
 - L'event qui vient de l'API calandar et qui est tout simplement la date du twig
 - Le helper qui est la personne qui aide margaux qui est affecté au twig
 - Les commentaires des personnes a propos du twig
 - ...d'autre choses a venir

- Un Helped est une personne isolé (Margaux)
- Un Helper est quelqu'un du reseau qui aide une personne isolé (Alex, Claire, Jean, Aurelien, Martine...)

Le pb maintenant.. Dans le twig controler, je recupère les twig depuis l'API google puis je veux iterer sur chaque twig pour y ajouter les commentaires, les helper, ..etc  avant de renvoyer au client un bon gros JSON bien complet.. Je me mélange les pinceaux entre les array et les objets ruby

Merci

**Comment by cblavier** [comment]
Il me manque des bases pour comprendre le code et t'aider

- à quoi correspond l'agenda google auquel on se connecte ? à qui appartient-il et que contient-il ?
- que doit faire l'API que tu développes ?

**Comment by robbee** [comment]
Ok ! Je te réponds ce soir !

++

Le lundi 9 mai 2016, Christian Blavier <notifications@github.com> a écrit :

> Il me manque des bases pour comprendre le code et t'aider
>
>    - à quoi correspond l'agenda google auquel on se connecte ? à qui
>    appartient-il et que contient-il ?
>    - que doit faire l'API que tu développes ?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/twigy/twigy-server/issues/1#issuecomment-217895877>
>


--

**Comment by robbee** [comment]
Coucou ! 

L'API google calendar c'est pour pas a avoir a gérer des événements date (ca peut vite être galère.. Notamment les récurrence ..i.e "tous les jeudi ou tous les jours de la semaine sauf we...etc).. On a fait se choix pour le MVP pour pas trop se galèrer .. et c'est plutot pratique. 

Du coup l'évenement est stocké dans le calendar google et tous le reste chez nous.. 

- On utilise mon compte google pour tous les calendar (on peut créer suffisament de calendar avec un compte google...) En tous cas suffisament pour le MVP
- Chaque aidé (helped = margaux) aura sont propre calandar (avec le calendarID) 
- Dans un événement google on renseigne le summary (soin, visite, repas, conduite, ...) et surtout l'id de l'aidant (En gros : la personne qui a pris cet événement) Pour cela on utilise des balises libres prévu par google (event.extended_properties.shared)

Voila un exemple d'event renvoyé par l'API. Tu peux observer le summary et surtout l'helpedId = ob3QEWrW5I (margaux) et l'helperId = 1 (alex)

`  {
   "kind": "calendar#event",
   "etag": "\"2923893335854000\"",
   "id": "pbha5sqnfnebbjct31phb6pf80",
   "status": "confirmed",
   "htmlLink": "https://www.google.com/calendar/event?eid=cGJoYTVzcW5mbmViYmpjdDMxcGhiNnBmODAgZGhxYzR2aDloOXNrcW9kaHBybzc3NjJvbjRAZw",
   "created": "2016-04-29T16:17:47.000Z",
   "updated": "2016-04-29T16:17:47.927Z",
   "summary": "conduite",
   "creator": {
    "email": "alexandre.bonte@gmail.com",
    "displayName": "Alexandre Bonte"
   },
   "organizer": {
    "email": "dhqc4vh9h9skqodhpro7762on4@group.calendar.google.com",
    "displayName": "Margaux",
    "self": true
   },
   "start": {
    "dateTime": "2016-04-29T18:15:41+02:00",
    "timeZone": "Europe/Paris"
   },
   "end": {
    "dateTime": "2016-04-29T18:15:41+02:00",
    "timeZone": "Europe/Paris"
   },
   "iCalUID": "pbha5sqnfnebbjct31phb6pf80@google.com",
   "sequence": 0,
   "extendedProperties": {
    "private": {
     "helpedId": "ob3QEWrW5I"
    },
    "shared": {
     "helper": "1",
     "shared1": "none"
    }
   },
   "reminders": {
    "useDefault": true
   }
  }`

Pour le client angular,  je voudrais renvoyé un objet json un peu plus complet (pret pour l'affichage). Avec les détails du helper et les details du helped (pas uniquement les id) et plus plein d'autres choses quand j'aurais compris comment on fait une jointure entre une json renvoyé par l'API et une liste d'objet renvoyé par activeRecord... Tu comprends le concept ? 

Autre option .. si j'arrive pas .. je vais tout flanquer dans l'évenement google avec les balises libres :-) je vais m'en servir comme DB !! 

Je suis capable !!! Même pas peur !!

Merci à toi et surtout n'hésite pas a m'appeler si je suis pas claire ..

++

**Comment by cblavier** [comment]
Merci c’est plus clair

Je ne peux pas suivre le process oauth pour me connecter à ton calendrier, car il faudrait que je sois loggé à ton compte. Ca me parait un peu bizarre cette librairie qui crée des fichiers en local juste pour se connecter à un calendrier. Pour moi il faudrait avoir un fichier de conf (commité avec le projet) qui contiennent simplement l’access_id et le secret pour se connecter en oauth.

Je vais essayer de te faire un exemple.

Sinon qq remarques sur le code :

- il faudrait bouger tout le code de connection au calendrier dans un service dédié (et garder dans le controlleur uniquement la logique de rendu)
- je trouve bizarre que tu aies fait des routes getAllTwig / addTwig / … au lieu de suivre les conventions REST. Dans routes.rb tu mets juste `resources :twigs`, ce qui te fais les routes suivantes (comme dans tes autres controlleurs en fait)
  - `POST getAllTwigs` devient `GET /twigs`
  - `POST addTwig` devient `POST /twigs`
  - `POST updateTwig` devient `PUT /twigs/:id`
  - `DELETE deleteTwig` devient `DELETE /twigs/:id`

**Comment by robbee** [comment]
Coucou

Je t'ai rajouté comme user sur le calendar de Margaux.. desolé. Par contre pour le ifchier on ne peux pas sourcer le fichier de secret .. le repo est public :-(

Ok pour le code de connection dans un service (nickel)

Pour les routes tu as raison .. j'ai fait le cochon désolé ! J'ai pas eu trop le temps de m'y remettre !

**Comment by cblavier** [comment]
Ok, j’essaie de te committer un bout de code dans pas longtemps.

Pour le fichier de secret je vais essayer de voir à stocker au moins les
client_id et refresh_token en variable d’environnement, ca simplifiera la
vie le jour ou tu voudras déployer sur heroku ou équivalent.


2016-05-11 11:41 GMT+02:00 Robbee <notifications@github.com>:

**Comment by cblavier** [comment]
Voir pull request: #2

**Comment by robbee** [comment]
Génial Christian !! Ca va carrément m'aider !! Merci bcp
