### ISSUE TITLE
Select with array

### ISSUE THREAD

**Issue by robbee** [twigy/twigy-server#4]
Hello Christian

J'ai un autre minuscule problème.. Toujours dans la construction du twig... Mais cette fois je suis sur un autre cas .. Les ressource_helper (Les ressource_helper sont les personnes qui dans un meme réseau partage les meme skill)

Ex : Toi et moi pouvons faire du `bricolage`, Martine prendre un `cafe`, jean et michel peuvent faire le `jardinage`

Donc en base sur la table Helper j'ai une colonne `skill` qui convient la liste des skill possible pour le helper (Un array : `t.string   "skill",  default: [], array: true`)

La ou ca merde c'est quand j'essaye :  `Helper.where("? = ANY (skill)", summary)`

ActiveRecord me dit `argument of WHERE must be type boolean, not type record`

Je pense que c'est pas bien compliqué mais... ;-)

Merci beaucoup 

Alex

PS : Je sais pas si tu test ta réponse mais j'ai changé d'API et donc de refresh token. Fait moi savoir si tu veux le nouveau... mon petit doigt me dit que tu n'as pas besoin (c'est écoeurant ) ;-)

**Comment by cblavier** [comment]
Pour le coup c'était pas trivial. Pour régler ce genre de problème je vais dans la console Rails (rails console), et je tente de reproduire le problème. 

Donc en faisant `Helper.where("? = ANY (skill)", ["bricolage", "jardinage"])` je me tape le même problème que toi.

Visiblement la syntaxe (bien pénible) à utiliser est : `Helper.where("ARRAY[?]::varchar[] && skill", ["bricolage", "jardinage"])` qui retourne la liste des helpers qui ont soit bricolage, soit jardinage dans leur skills. Je ne suis pas sûr à 100% que ce soit ça que tu veux : si tu veux peut être les helpers qui ont toutes les skills requises, il faut remplacer `&&` par `<@` (trivial)

Au passage, tu devrais renommer le champ `skill` en `skills`, ca rendra la compréhension plus simple.

Bon courage

**Comment by robbee** [comment]
Merci beaucoup Christian !!! T'es un chief !! 

Bonne après midi :-)

**Comment by robbee** [comment]
Rrrrg ! Du coup maintenant je bloque à l’étape juste après.. c'est moche la vie :-(

Quand je fais le hash, j'ai bien `{["visite"]=>[avec deux helpers]}` mais j'ai aussi `{["jardinage","bricolage"]=>[]}` 

La clef de hash est pourrave.. Faudrait `{["visite"]=>[helpers...]` `{["jardinage"]=>[helpers...]` et `{["bricolage"]=>[helpers...]`

Comme ca quand je recolle les ressource_helpers a l'event (qui lui n'a qu'un seul skill=summary) et bien je suis peinard !

Tu vois le style ?

Désolé de t’embêter avec ca... si tu peux pas n’hésite pas a me le dire !!

**Comment by cblavier** [comment]
Tu ne devrais pas affecter le tableau de skills comme clé de hash du coup.
Quand tu reçois ton tableau de skills tu itères sur chacune des skill et tu les utilises comme clé. 

Un truc comme ça :
```
ressource_helpers_by_ids = ressource_helpers.inject({}) { |hash, ressource_helper|
  ressource_helper.skill.each do |skill|
    hash[skill] ||= []
    hash[skill] << ressource_helper
  end
  hash
}
```

**Comment by robbee** [comment]
Right ! perfect !! merci
